version: "2"

services:
   mail:
      image: mailhog/mailhog
      container_name: mail
      restart: always
      ports:
        - 1025:1025
        - 8025:8025
   db:
       image: mysql:5.7
       command: --innodb_use_native_aio=0
       container_name: mysql57
       restart: always
       ports:
        - 3306:3306
       volumes:
       - ../mysql:/var/lib/mysql
       environment:
           MYSQL_ROOT_PASSWORD: root
   php:
       build: ./php
       container_name: php72
       restart: always
       working_dir: /var/www
       volumes:
       - ../:/var/www
       links:
       - db
       - mail
   nginx:
       build: ./nginx
       container_name: nginx
       restart: always
       ports:
       - 80:80
       volumes_from:
       - php
       restart: always
       links:
       - php
       - mail